@startuml

package Enemy {
    [AI Movement Behaviour] as aiMovementBeh
    [Movement Feature] as movementFea
    [Player Tracking Feature] as playerTrackingFea
}

aiMovementBeh -- movementFea
aiMovementBeh -- playerTrackingFea

@enduml