@startuml

package Enemy {
    [Target Movement Behaviour] as targetMovementBeh
    [Damageable Behaviour] as damageableBeh
    [Inflict Damage On Collision Behaviour] as inflictDamageBeh
    [Drop Behaviour] as dropBeh
    [Movement Feature] as movementFea
    [Health Feature] as healthFea
    [Inflict Damage On Collision Feature] as inflictDamageFea
    [Tracking Feature] as trackingFea
    [Loot Feature] as lootFea
}

targetMovementBeh --- movementFea
targetMovementBeh --- trackingFea

inflictDamageBeh -- inflictDamageFea

damageableBeh -- healthFea

dropBeh --- healthFea
dropBeh --- lootFea

@enduml