@startuml

package Player {
    [Player Input] as playerInput
    [Movement Behaviour] as movementBeh
    [Armed Behaviour] as armedBeh
    [Movement Feature] as movementFea
    [Owned Weapon Feature] as weaponFea
    [Ability Feature] as abilityFea
}

movementBeh -- movementFea
movementBeh -- abilityFea

armedBeh -- weaponFea
armedBeh -- abilityFea

playerInput .. movementBeh

@enduml